openapi: 3.0.0
info:
  title: Scribe App
  description: |
    An Application that helps you capture what you are reading and compile notes!
  version: 1.0.0
servers:
  - url: http://localhost:3030/api
    description: localhost
paths:
  /text/{uri}:
    get:
      summary: Get information related to a Text
      description: Retrieves the the Text by id
      operationId: get-text
      parameters:
        - name: uri
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/text"
  /text:
    post:
      summary: Post information related to a new Text
      description: Creates a new Text
      operationId: post-text
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newText"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/text"

components:
  schemas:
    errorMessage:
      type: string
      maxLength: 256
      description: A text message describing an error
    text:
      allOf:
        - $ref: "#/components/schemas/newText"
        - required:
            - uri
          properties:
            uri:
              type: string
              description: Unique id of the Text

    newText:
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the Text
        author:
          type: string
          description: Author of the Text
