// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by  version  DO NOT EDIT.
package ports

// NewText defines model for newText.
type NewText struct {
	// Author of the Text
	Author *string `json:"author,omitempty"`

	// Name of the Text
	Name string `json:"name"`
}

// Text defines model for text.
type Text struct {
	// Embedded struct due to allOf(#/components/schemas/newText)
	NewText `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// Unique id of the Text
	Uri string `json:"uri"`
}

// PostTextJSONBody defines parameters for PostText.
type PostTextJSONBody NewText

// PostTextJSONRequestBody defines body for PostText for application/json ContentType.
type PostTextJSONRequestBody PostTextJSONBody
