// Package Scribe provides primitives to interact with the openapi HTTP API.
//
// Code generated by  version  DO NOT EDIT.
package model

// Text defines model for text.
type Text struct {
	// The author of the text
	Author *string `json:"author,omitempty"`

	// The name of the text
	Name *string `json:"name,omitempty"`

	// Uique identifier for the text
	Uri *string `json:"uri,omitempty"`
}
